### PR TITLE
Client testing

### PR DESCRIPTION
**Pull request by ahchung23**
- Renders FE with react-router
    - Page renders a different book for id's 1-100 for /books/:id
- All FE components rendered with css stylings
    - Used styled-components and inline react styling
- Tooltip shows when hovered over. Used CSS in styled-components to do this and kept Tooltip a functional component.
    - The tooltip is rendered onto dom initially, but has display property of “none” so cannot be seen.
    - Tooltip display property changes to “block” while the Edition component is moused over.

**Basic structure of front end looks like this:**

```
App 
  |--Header 
  |      |--DetailDataBox
  |                     |--MainInfo
  |                     |--Characters
  |                     |--Settings
  |                     |--Awards
  |
  |--Other Editions
                |--Edition 
                         |--Tooltip 
                                  |--Stars
```

**Question:**
What do you think about my overall FE component structure design? Do you see any way to simplify or make the structure better?
What do you think about the design of the state in individual components?

**Notes:**
Server-side tests edited to be independent of the database by using mocked functions.
Finished writing/passing all client-side tests for components (12 test suites, 64 tests).
Used jest with supertest and enzyme.

**Feedback appreciated!**

### CODE REVIEW

**Comment by kazshige** [comment]
you can try to be consistent with the folder and file naming conventions. It is preferable you stick with "PascalCase" for folders and "camelCase" for files

**Comment by kazshige** [comment]
"What do you think about my overall FE component structure design? Do you see any way to simplify or make the structure better?" Overall I think the whole design concept is nice although it is not the same as the sketch you have up there which was a little confusing. The main feedback I will give here is to move the "app.js" file i.e your app root/entry file away from the component folder and let it be on the same directory with the index.jsx because components are only supposed to contain the reusable parts of your application UI

**Comment by kazshige** [comment]
"What do you think about the design of the state in individual components?"

I think the implementation is okay.

**Comment by ahchung23** [comment]
@kazshige 
Thanks for the review! I fixed my folder naming convention and moved my files around for better organization as you suggested. 

 And sorry about the confusion! The basic component nesting structure looks like this!

```
App 
  |--Header 
       |--DetailDataBox
       |        |--MainInfo
       |        |--Characters
       |        |--Settings
       |        |--Awards
       |
       |--Other Editions
              |--Edition 
              |--Tooltip 
              |--Stars   
```

**Pull request merged**
